import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'
import { formatCurrency as formatCurrencyFn, getCurrencySymbol, getCurrentCurrency } from '../../config/currency'

export type Language = 'en' | 'ar' | 'ur'
export type Currency = 'USD' | 'PKR' | 'EGP' | 'SAR' | 'BHD' | 'OMR' | 'AED' | 'ZAR'

export interface CurrencyInfo {
  code: Currency
  symbol: string
  name: string
  country: string
}

export const currencies: Record<Currency, CurrencyInfo> = {
  USD: { code: 'USD', symbol: '$', name: 'US Dollar', country: 'United States' },
  PKR: { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', country: 'Pakistan' },
  EGP: { code: 'EGP', symbol: '£', name: 'Egyptian Pound', country: 'Egypt' },
  SAR: { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', country: 'Saudi Arabia' },
  BHD: { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', country: 'Bahrain' },
  OMR: { code: 'OMR', symbol: '﷼', name: 'Omani Rial', country: 'Oman' },
  AED: { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', country: 'UAE' },
  ZAR: { code: 'ZAR', symbol: 'R', name: 'South African Rand', country: 'South Africa' }
}

export interface LanguageInfo {
  code: Language
  name: string
  nativeName: string
  direction: 'ltr' | 'rtl'
}

export const languages: Record<Language, LanguageInfo> = {
  en: { code: 'en', name: 'English', nativeName: 'English', direction: 'ltr' },
  ar: { code: 'ar', name: 'Arabic', nativeName: 'العربية', direction: 'rtl' },
  ur: { code: 'ur', name: 'Urdu', nativeName: 'اردو', direction: 'rtl' }
}

interface InternationalizationContextType {
  language: Language
  currency: Currency
  currentLanguage: Language
  currentCurrency: CurrencyInfo
  currencies: CurrencyInfo[]
  direction: 'ltr' | 'rtl'
  setLanguage: (language: Language) => void
  setCurrency: (currency: Currency) => void
  t: (key: string, params?: Record<string, any>) => string
  formatCurrency: (amount: number, currency?: Currency) => string
  formatNumber: (number: number) => string
}

const InternationalizationContext = createContext<InternationalizationContextType | undefined>(undefined)

// Translation keys and messages
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    
    // Dashboard Navigation
    'nav.overview': 'Overview',
    'nav.sales': 'Sales',
    'nav.bookings': 'Bookings',
    'nav.expenses': 'Expenses',
    'nav.commissions': 'Commissions',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.userManagement': 'User Management',
    'nav.vendorManagement': 'Vendor Management',
    'nav.materialManagement': 'Material Management',
    'nav.procurement': 'Procurement',
    'nav.purchaseOrders': 'Purchase Orders',
    'nav.projectMilestones': 'Project Milestones',
    
    // Settings
    'settings.title': 'Organization Settings',
    'settings.description': 'Customize your branding, themes, and templates',
    'settings.language': 'Language',
    'settings.currency': 'Currency',
    'settings.languageDescription': 'Choose your preferred language',
    'settings.currencyDescription': 'Select your organization\'s default currency',
    'settings.saveChanges': 'Save Changes',
    'settings.localization': 'Localization',
    'settings.localizationDescription': 'Language and regional settings',
    
    // Currency Names
    'currency.USD': 'US Dollar',
    'currency.PKR': 'Pakistani Rupee', 
    'currency.EGP': 'Egyptian Pound',
    'currency.SAR': 'Saudi Riyal',
    'currency.BHD': 'Bahraini Dinar',
    'currency.OMR': 'Omani Rial',
    'currency.AED': 'UAE Dirham',
    'currency.ZAR': 'South African Rand',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signOut': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.createAccount': 'Create Account',
    
    // Overview Dashboard
    'overview.title': 'Dashboard Overview',
    'overview.totalRevenue': 'Total Revenue',
    'overview.activeProjects': 'Active Projects',
    'overview.pendingApprovals': 'Pending Approvals',
    'overview.upcomingMilestones': 'Upcoming Milestones',
    
    // Sales
    'sales.title': 'Sales Management',
    'sales.description': 'Track unit bookings, customer payments, and sales performance',
    'sales.newSale': 'New Sale',
    'sales.addBooking': 'Add Booking',
    'sales.newBooking': 'New Unit Booking',
    'sales.newBookingDescription': 'Record a new customer booking',
    'sales.unitNumber': 'Unit Number',
    'sales.unitPlaceholder': 'e.g., A-101',
    'sales.customerName': 'Customer Name',
    'sales.customerPlaceholder': 'Full name',
    'sales.emailPlaceholder': 'customer@email.com',
    'sales.phone': 'Phone',
    'sales.phonePlaceholder': '+1-555-0123',
    'sales.totalAmount': 'Total Amount',
    'sales.downPayment': 'Down Payment',
    'sales.createBooking': 'Create Booking',
    'sales.monthlyGrowth': '+15% from last month',
    'sales.unitsBooked': 'Units Booked',
    'sales.ofTotalUnits': 'of {{total}} total units',
    'sales.commissionRate': '5% commission rate',
    'sales.activeCustomers': 'Active Customers',
    'sales.weeklyGrowth': '+3 this week',
    'sales.progress': 'Sales Progress',
    'sales.progressDescription': 'Unit booking progress for current project',
    'sales.booked': 'Booked',
    'sales.sold': 'Sold',
    'sales.available': 'Available',
    'sales.records': 'Sales Records',
    'sales.recordsDescription': 'Customer bookings and payment status',
    'sales.allStatus': 'All Status',
    'sales.pending': 'Pending',
    'sales.completed': 'Completed',
    'sales.unit': 'Unit',
    'sales.customer': 'Customer',
    'sales.contact': 'Contact',
    'sales.agent': 'Agent',
    'sales.status': 'Status',
    'sales.date': 'Date',
    'sales.totalSales': 'Total Sales',
    'sales.pendingSales': 'Pending Sales',
    'sales.completedSales': 'Completed Sales',
    
    // Expenses
    'expenses.title': 'Expense Management',
    'expenses.description': 'Track and approve project expenses with comprehensive maker-checker workflow',
    'expenses.newExpense': 'New Expense',
    'expenses.submitNewExpense': 'Submit New Expense',
    'expenses.submitDescription': 'Submit a new expense for approval through the maker-checker workflow',
    'expenses.totalApproved': 'Total Approved',
    'expenses.expensesApproved': '{{count}} expenses approved',
    'expenses.pendingApproval': 'Pending Approval',
    'expenses.awaitingReview': '{{count}} awaiting review',
    'expenses.thisMonth': 'This Month',
    'expenses.monthlyChange': '5% vs last month',
    'expenses.requireResubmission': 'Require resubmission',
    'expenses.approved': 'Approved',
    'expenses.rejected': 'Rejected',
    
    // Projects
    'projects.title': 'Projects',
    'projects.newProject': 'New Project',
    'projects.activeProjects': 'Active Projects',
    'projects.completedProjects': 'Completed Projects',

    // Bookings Dashboard
    'bookings.title': 'Bookings & Sales',
    'bookings.description': 'Manage unit bookings, payments, and sales tracking',
    'bookings.recordPayment': 'Record Payment',
    'bookings.newBooking': 'New Booking',
    'bookings.allBookings': 'All Bookings',
    'bookings.installments': 'Installments',
    'bookings.payments': 'Payments',
    'bookings.salesTargets': 'Sales Targets',
    'bookings.unitBookings': 'Unit Bookings',
    'bookings.unit': 'Unit',
    'bookings.customer': 'Customer',
    'bookings.amount': 'Amount',
    'bookings.bookingDate': 'Booking Date',
    'bookings.salesAgent': 'Sales Agent',
    'bookings.status': 'Status',
    'bookings.actions': 'Actions',
    'bookings.viewDetails': 'View Details',
    'bookings.discount': 'discount',
    'bookings.newUnitBooking': 'New Unit Booking',
    'bookings.newBookingDescription': 'Create a new booking by entering customer details, selecting a unit, and choosing a payment plan.',
    'bookings.customerDetails': 'Customer Details',
    'bookings.unitSelection': 'Unit Selection',
    'bookings.paymentPlan': 'Payment Plan',
    'bookings.confirmation': 'Confirmation',
    'bookings.customerName': 'Customer Name',
    'bookings.fullName': 'Full name',
    'bookings.email': 'Email',
    'bookings.phoneNumber': 'Phone Number',
    'bookings.address': 'Address',
    'bookings.completeAddress': 'Complete address',
    'bookings.unitType': 'Unit Type',
    'bookings.selectUnitType': 'Select unit type',
    'bookings.availableUnits': 'Available Units',
    'bookings.selectUnit': 'Select unit',
    'bookings.area': 'Area (sq ft)',
    'bookings.ratePerSqFt': 'Rate per sq ft',
    'bookings.baseAmount': 'Base Amount',
    'bookings.discountPercent': 'Discount %',
    'bookings.selectPaymentPlan': 'Select Payment Plan',
    'bookings.standardPlan': 'Standard Plan - 24 Months',
    'bookings.standardPlanDesc': '20% down payment, Monthly installments',
    'bookings.quickPlan': 'Quick Payment - 12 Months',
    'bookings.quickPlanDesc': '30% down payment, Quarterly installments',
    'bookings.booking': 'Booking',
    'bookings.registration': 'Registration',
    'bookings.balance': 'Balance',
    'bookings.constructionLinked': 'Construction Linked',
    'bookings.bookingSummary': 'Booking Summary',
    'bookings.finalAmount': 'Final Amount',
    'bookings.bookingAmountDue': 'Booking Amount Due',
    'bookings.confirmBooking': 'Confirm Booking',
    'bookings.bookingCreated': 'Booking created successfully!',
    'bookings.recordPaymentTitle': 'Record Payment',
    'bookings.recordPaymentDesc': 'Record a payment received for a specific booking installment with transaction details.',
    'bookings.bookingReference': 'Booking Reference',
    'bookings.selectBooking': 'Select booking',
    'bookings.installment': 'Installment',
    'bookings.selectInstallment': 'Select installment',
    'bookings.paymentAmount': 'Payment Amount',
    'bookings.amountReceived': 'Amount received',
    'bookings.paymentMethod': 'Payment Method',
    'bookings.selectMethod': 'Select method',
    'bookings.cash': 'Cash',
    'bookings.cheque': 'Cheque',
    'bookings.bankTransfer': 'Bank Transfer',
    'bookings.upi': 'UPI',
    'bookings.referenceNumber': 'Reference Number',
    'bookings.transactionNumber': 'Transaction/Cheque number',
    'bookings.paymentDate': 'Payment Date',
    'bookings.recordPaymentSuccess': 'Payment recorded successfully!',
    'bookings.bookingDetails': 'Booking Details',
    'bookings.bookingDetailsDesc': 'Complete booking information and payment schedule',
    'bookings.customerInformation': 'Customer Information',
    'bookings.name': 'Name',
    'bookings.phone': 'Phone',
    'bookings.unitInformation': 'Unit Information',
    'bookings.type': 'Type',
    'bookings.financialDetails': 'Financial Details',
    'bookings.totalAmount': 'Total Amount',
    'bookings.installmentSchedule': 'Installment Schedule',
    'bookings.milestone': 'Milestone',
    'bookings.dueDate': 'Due Date',
    'bookings.close': 'Close',
    'bookings.downloadAgreement': 'Download Agreement',
    'bookings.agreementDownloaded': 'Booking agreement downloaded!',
    'bookings.booked': 'booked',
    'bookings.registered': 'registered',
    'bookings.cancelled': 'cancelled',
    'bookings.completed': 'completed',
    'bookings.paid': 'paid',
    'bookings.pending': 'pending',
    'bookings.overdue': 'overdue',

    // Commissions Dashboard
    'commissions.title': 'Commission Management',
    'commissions.description': 'Track agent performance and commission payouts',
    'commissions.totalPaid': 'Total Paid',
    'commissions.pending': 'Pending',
    'commissions.thisMonth': 'This Month',
    'commissions.averageRate': 'Average Rate',
    'commissions.payments': 'payments',
    'commissions.awaitingPayment': 'awaiting payment',
    'commissions.monthlyGrowthPercent': '+22% from last month',
    'commissions.standardRate': 'Standard commission rate',
    'commissions.agentPerformance': 'Agent Performance',
    'commissions.agentPerformanceDesc': 'Commission earnings by sales agent',
    'commissions.unitsSold': 'Units Sold',
    'commissions.totalCommission': 'Total Commission',
    'commissions.performance': 'Performance',
    'commissions.commissionRecords': 'Commission Records',
    'commissions.commissionRecordsDesc': 'Detailed commission tracking and payment history',
    'commissions.agent': 'Agent',
    'commissions.saleDate': 'Sale Date',
    'commissions.customer': 'Customer',
    'commissions.saleAmount': 'Sale Amount',
    'commissions.commission': 'Commission',
    'commissions.paidDate': 'Paid Date',
    'commissions.processPayment': 'Process Payment',

    // Overview Dashboard - Additional Keys
    'overview.welcomeBack': 'Welcome back, {{name}}. Here\'s what\'s happening with your projects.',
    'overview.totalInvestment': 'Total Investment',
    'overview.currentCashBalance': 'Current Cash Balance',
    'overview.totalExpenses': 'Total Expenses',
    'overview.projectRevenue': 'Project Revenue',
    'overview.budgetRemaining': 'Budget Remaining',
    'overview.monthlyExpenses': 'Monthly Expenses',
    'overview.cashAvailable': 'Cash Available',
    'overview.unitsBooked': 'Units Booked',
    'overview.monthlySales': 'Monthly Sales',
    'overview.commissionEarned': 'Commission Earned',
    'overview.activeCustomers': 'Active Customers',
    'overview.totalBudget': 'Total Budget',
    'overview.cashBalance': 'Cash Balance',
    'overview.netRevenue': 'Net Revenue',
    'overview.budgetUtilization': 'Budget Utilization',
    'overview.budgetUsed': '{{used}} of {{total}} used',
    'overview.salesProgress': 'Sales Progress',
    'overview.unitsBookedOf': '{{booked}} of {{total}} units booked',
    'overview.recentActivity': 'Recent Activity',
    'overview.recentActivityDesc': 'Latest updates from your projects',
    'overview.newUnitBooking': 'New unit booking',
    'overview.unitBookedBy': 'Unit {{unit}} booked by {{customer}}',
    'overview.expenseApprovalPending': 'Expense approval pending',
    'overview.constructionMaterials': 'Construction materials - {{amount}}',
    'overview.paymentReceived': 'Payment received',
    'overview.installmentPayment': 'Installment payment from {{customer}}',
    'overview.budgetMilestone': 'Budget milestone reached',
    'overview.budgetUtilized': '{{percent}}% of construction budget utilized',
    'overview.hoursAgo': '{{hours}} hours ago',
    'overview.dayAgo': '{{days}} day ago',
    'overview.allocated': 'Allocated',
    'overview.available': 'Available',
    'overview.waiting': '{{count}} waiting',
    'overview.units': 'units',
    'overview.thisWeek': '+{{count}} this week',

    // User Management Dashboard
    'userManagement.title': 'User Management',
    'userManagement.description': 'Manage user accounts, permissions, and organization settings',
    'userManagement.inviteUser': 'Invite User',
    'userManagement.activeUsers': 'Active Users',
    'userManagement.pendingInvitations': 'Pending Invitations',
    'userManagement.totalUsers': 'Total Users',
    'userManagement.newThisMonth': 'New This Month',
    'userManagement.userGrowth': '+{{percent}}% user growth',
    'userManagement.invitationsSent': '{{count}} invitations sent',
    'userManagement.userDetails': 'User Details',
    'userManagement.role': 'Role',
    'userManagement.lastActive': 'Last Active',
    'userManagement.joinDate': 'Join Date',
    'userManagement.editUser': 'Edit User',
    'userManagement.deleteUser': 'Delete User',
    'userManagement.invitationStatus': 'Invitation Status',
    'userManagement.sentDate': 'Sent Date',
    'userManagement.resendInvitation': 'Resend Invitation',
    'userManagement.cancelInvitation': 'Cancel Invitation',

    // Material Management Dashboard
    'materials.title': 'Material Management',
    'materials.description': 'Track material inventory, usage, and procurement requirements',
    'materials.addMaterial': 'Add Material',
    'materials.createPO': 'Create PO',
    'materials.totalMaterials': 'Total Materials',
    'materials.categoriesManaged': 'categories managed',
    'materials.lowStock': 'Low Stock',
    'materials.itemsNeedReorder': 'items need reorder',
    'materials.thisMonth': 'This Month',
    'materials.consumed': 'Consumed',
    'materials.materialsUsed': 'materials used',
    'materials.categories': 'Categories',
    'materials.category': 'Category',
    'materials.quantity': 'Quantity',
    'materials.unit': 'Unit',
    'materials.unitCost': 'Unit Cost',
    'materials.totalValue': 'Total Value',
    'materials.supplier': 'Supplier',
    'materials.lastUpdated': 'Last Updated',
    'materials.stockLevel': 'Stock Level',
    'materials.reorderLevel': 'Reorder Level',
    'materials.viewDetails': 'View Details',

    // Vendor Management Dashboard
    'vendors.title': 'Vendor Management',
    'vendors.description': 'Manage vendor relationships, contracts, and performance tracking',
    'vendors.addVendor': 'Add Vendor',
    'vendors.totalVendors': 'Total Vendors',
    'vendors.activeContracts': 'Active Contracts',
    'vendors.pendingPayments': 'Pending Payments',
    'vendors.averageRating': 'Average Rating',
    'vendors.ratingOutOf5': 'out of 5 stars',
    'vendors.activeVendors': 'Active Vendors',
    'vendors.vendorName': 'Vendor Name',
    'vendors.contactPerson': 'Contact Person',
    'vendors.phone': 'Phone',
    'vendors.email': 'Email',
    'vendors.services': 'Services',
    'vendors.rating': 'Rating',
    'vendors.status': 'Status',
    'vendors.actions': 'Actions',
    'vendors.edit': 'Edit',
    'vendors.viewContracts': 'View Contracts',

    // Procurement Dashboard
    'procurement.title': 'Procurement Management',
    'procurement.description': 'Manage procurement requests, approvals, and vendor selection',
    'procurement.newRequest': 'New Request',
    'procurement.totalRequests': 'Total Requests',
    'procurement.awaitingApproval': 'Awaiting Approval',
    'procurement.approvedValue': 'Approved Value',
    'procurement.thisMonth': 'This Month',
    'procurement.processed': 'Processed',
    'procurement.requestsProcessed': 'requests processed',
    'procurement.procurementRequests': 'Procurement Requests',
    'procurement.requestId': 'Request ID',
    'procurement.requestedBy': 'Requested By',
    'procurement.amount': 'Amount',
    'procurement.status': 'Status',
    'procurement.requestDate': 'Request Date',
    'procurement.actions': 'Actions',
    'procurement.approve': 'Approve',
    'procurement.reject': 'Reject',
    'procurement.review': 'Review',

    // Purchase Orders Dashboard
    'purchaseOrders.title': 'Purchase Orders',
    'purchaseOrders.description': 'Create and manage purchase orders for materials and services',
    'purchaseOrders.createPO': 'Create PO',
    'purchaseOrders.totalPOs': 'Total POs',
    'purchaseOrders.awaitingDelivery': 'Awaiting Delivery',
    'purchaseOrders.totalValue': 'Total Value',
    'purchaseOrders.thisMonth': 'This Month',
    'purchaseOrders.created': 'Created',
    'purchaseOrders.poNumber': 'PO Number',
    'purchaseOrders.vendor': 'Vendor',
    'purchaseOrders.items': 'Items',
    'purchaseOrders.amount': 'Amount',
    'purchaseOrders.status': 'Status',
    'purchaseOrders.orderDate': 'Order Date',
    'purchaseOrders.expectedDelivery': 'Expected Delivery',
    'purchaseOrders.actions': 'Actions',
    'purchaseOrders.viewPO': 'View PO',

    // Reports Dashboard
    'reports.title': 'Reports & Analytics',
    'reports.description': 'Generate comprehensive reports and analytics for project insights',
    'reports.generateReport': 'Generate Report',
    'reports.financialReports': 'Financial Reports',
    'reports.salesReports': 'Sales Reports',
    'reports.expenseReports': 'Expense Reports',
    'reports.projectReports': 'Project Reports',
    'reports.exportPDF': 'Export PDF',
    'reports.exportExcel': 'Export Excel',
    'reports.dateRange': 'Date Range',
    'reports.selectRange': 'Select date range',
    'reports.reportType': 'Report Type',
    'reports.selectType': 'Select report type',

    // Project Setup Dashboard
    'projectSetup.title': 'Project Setup',
    'projectSetup.description': 'Configure new projects with basic information, budgets, and milestones',
    'projectSetup.newProject': 'New Project',
    'projectSetup.activeProjects': 'Active Projects',
    'projectSetup.completedProjects': 'Completed Projects',
    'projectSetup.totalBudget': 'Total Budget',
    'projectSetup.projectName': 'Project Name',
    'projectSetup.location': 'Location',
    'projectSetup.startDate': 'Start Date',
    'projectSetup.expectedCompletion': 'Expected Completion',
    'projectSetup.status': 'Status',
    'projectSetup.progress': 'Progress',
    'projectSetup.actions': 'Actions',
    'projectSetup.viewProject': 'View Project',
    'projectSetup.editProject': 'Edit Project',

    // Project Milestones Dashboard
    'milestones.title': 'Project Milestones',
    'milestones.description': 'Track project progress through key milestones and deliverables',
    'milestones.addMilestone': 'Add Milestone',
    'milestones.totalMilestones': 'Total Milestones',
    'milestones.completed': 'Completed',
    'milestones.inProgress': 'In Progress',
    'milestones.upcoming': 'Upcoming',
    'milestones.milestoneName': 'Milestone Name',
    'milestones.project': 'Project',
    'milestones.targetDate': 'Target Date',
    'milestones.actualDate': 'Actual Date',
    'milestones.status': 'Status',
    'milestones.progress': 'Progress',
    'milestones.actions': 'Actions',
    'milestones.markComplete': 'Mark Complete',
    'milestones.updateProgress': 'Update Progress',

    // Employee Management Dashboard
    'employees.title': 'Employee Management',
    'employees.description': 'Manage employee records, attendance, and performance tracking',
    'employees.addEmployee': 'Add Employee',
    'employees.totalEmployees': 'Total Employees',
    'employees.activeEmployees': 'Active Employees',
    'employees.onLeave': 'On Leave',
    'employees.newHires': 'New Hires',
    'employees.employeeName': 'Employee Name',
    'employees.department': 'Department',
    'employees.position': 'Position',
    'employees.joinDate': 'Join Date',
    'employees.phone': 'Phone',
    'employees.email': 'Email',
    'employees.status': 'Status',
    'employees.actions': 'Actions',
    'employees.viewProfile': 'View Profile',
    'employees.editEmployee': 'Edit Employee',

    // Marketing Communication Dashboard
    'marketing.title': 'Marketing & Communication',
    'marketing.description': 'Manage marketing campaigns, customer communication, and lead generation',
    'marketing.newCampaign': 'New Campaign',
    'marketing.activeCampaigns': 'Active Campaigns',
    'marketing.totalLeads': 'Total Leads',
    'marketing.conversionRate': 'Conversion Rate',
    'marketing.campaignROI': 'Campaign ROI',
    'marketing.campaignName': 'Campaign Name',
    'marketing.type': 'Type',
    'marketing.startDate': 'Start Date',
    'marketing.endDate': 'End Date',
    'marketing.budget': 'Budget',
    'marketing.spent': 'Spent',
    'marketing.leads': 'Leads',
    'marketing.conversions': 'Conversions',
    'marketing.actions': 'Actions',
    'marketing.viewCampaign': 'View Campaign',
    'marketing.editCampaign': 'Edit Campaign',

    // Account Statements Dashboard
    'accountStatements.title': 'Account Statements',
    'accountStatements.description': 'View and manage financial account statements and transaction history',
    'accountStatements.generateStatement': 'Generate Statement',
    'accountStatements.accountBalance': 'Account Balance',
    'accountStatements.monthlyInflow': 'Monthly Inflow',
    'accountStatements.monthlyOutflow': 'Monthly Outflow',
    'accountStatements.pendingTransactions': 'Pending Transactions',
    'accountStatements.transactionHistory': 'Transaction History',
    'accountStatements.date': 'Date',
    'accountStatements.type': 'Type',
    'accountStatements.amount': 'Amount',
    'accountStatements.balance': 'Balance',
    'accountStatements.reference': 'Reference',
    'accountStatements.status': 'Status',

    // Auto Invoice System Dashboard
    'autoInvoice.title': 'Auto Invoice System',
    'autoInvoice.description': 'Automated invoice generation and management for milestone-based billing',
    'autoInvoice.createInvoice': 'Create Invoice',
    'autoInvoice.totalInvoices': 'Total Invoices',
    'autoInvoice.pendingInvoices': 'Pending Invoices',
    'autoInvoice.paidInvoices': 'Paid Invoices',
    'autoInvoice.overdueInvoices': 'Overdue Invoices',
    'autoInvoice.invoiceNumber': 'Invoice Number',
    'autoInvoice.customer': 'Customer',
    'autoInvoice.amount': 'Amount',
    'autoInvoice.issueDate': 'Issue Date',
    'autoInvoice.dueDate': 'Due Date',
    'autoInvoice.status': 'Status',
    'autoInvoice.actions': 'Actions',
    'autoInvoice.viewInvoice': 'View Invoice',
    'autoInvoice.sendReminder': 'Send Reminder',

    // Installments Invoicing Dashboard
    'installments.title': 'Installments & Invoicing',
    'installments.description': 'Manage installment schedules and automated invoice generation',
    'installments.generateInvoices': 'Generate Invoices',
    'installments.totalInstallments': 'Total Installments',
    'installments.dueThisMonth': 'Due This Month',
    'installments.overdue': 'Overdue',
    'installments.collected': 'Collected',
    'installments.installmentSchedule': 'Installment Schedule',
    'installments.customer': 'Customer',
    'installments.unit': 'Unit',
    'installments.milestone': 'Milestone',
    'installments.amount': 'Amount',
    'installments.dueDate': 'Due Date',
    'installments.status': 'Status',
    'installments.actions': 'Actions',
    'installments.generateInvoice': 'Generate Invoice',
    'installments.recordPayment': 'Record Payment',

    // Profile Settings
    'profile.settings': 'Profile Settings',
    'profile.manage_preferences': 'Manage your account settings and preferences',
    'profile.profile': 'Profile',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Privacy',
    'profile.security': 'Security',
    'profile.preferences': 'Preferences',
    'profile.personal_information': 'Personal Information',
    'profile.personal_info_description': 'Update your personal details and contact information',
    'profile.change_photo': 'Change Photo',
    'profile.photo_requirements': 'JPG or PNG, max 2MB',
    'profile.first_name': 'First Name',
    'profile.last_name': 'Last Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.address': 'Address',
    'profile.bio': 'Bio',
    'profile.department': 'Department',
    'profile.job_title': 'Job Title',
    'profile.current_password': 'Current Password',
    'profile.new_password': 'New Password',
    'profile.confirm_password': 'Confirm Password',
    'profile.enter_current_password': 'Enter your current password',
    'profile.enter_new_password': 'Enter a new password',
    'profile.confirm_new_password': 'Confirm your new password',
    'profile.update_password': 'Update Password',
    'profile.two_factor_auth': 'Two-Factor Authentication',
    'profile.two_factor_description': 'Add an extra layer of security to your account',
    'profile.session_timeout': 'Session Timeout',
    'profile.minutes': 'minutes',
    'profile.hour': 'hour',
    'profile.hours': 'hours',
    'profile.multiple_sessions': 'Allow Multiple Sessions',
    'profile.multiple_sessions_description': 'Allow login from multiple devices simultaneously',
    'profile.language_region': 'Language & Region',
    'profile.language_region_description': 'Customize your language and regional preferences',
    'profile.language': 'Language',
    'profile.currency': 'Currency',
    'profile.timezone': 'Timezone',
    'profile.date_format': 'Date Format',
    'profile.time_format': 'Time Format',
    'profile.saved_successfully': 'Profile saved successfully!',
    'profile.save_error': 'Failed to save profile. Please try again.'
  },
  
  ar: {
    // Navigation & Common  
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.loading': 'جارٍ التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.warning': 'تحذير',
    'common.info': 'معلومات',
    
    // Dashboard Navigation
    'nav.overview': 'نظرة عامة',
    'nav.sales': 'المبيعات',
    'nav.bookings': 'الحجوزات',
    'nav.expenses': 'المصروفات',
    'nav.commissions': 'العمولات',
    'nav.reports': 'التقارير',
    'nav.settings': 'الإعدادات',
    'nav.userManagement': 'إدارة المستخدمين',
    'nav.vendorManagement': 'إدارة الموردين',
    'nav.materialManagement': 'إدارة المواد',
    'nav.procurement': 'المشتريات',
    'nav.purchaseOrders': 'أوامر الشراء',
    'nav.projectMilestones': 'معالم المشروع',
    
    // Settings
    'settings.title': 'إعدادات المؤسسة',
    'settings.description': 'تخصيص العلامة التجارية والثيمات والقوالب',
    'settings.language': 'اللغة',
    'settings.currency': 'العملة',
    'settings.languageDescription': 'اختر لغتك المفضلة',
    'settings.currencyDescription': 'حدد العملة الافتراضية لمؤسستك',
    'settings.saveChanges': 'حفظ التغييرات',
    'settings.localization': 'الترجمة والمحلية',
    'settings.localizationDescription': 'إعدادات اللغة والمنطقة',
    
    // Currency Names
    'currency.USD': 'الدولار الأمريكي',
    'currency.PKR': 'الروبية الباكستانية',
    'currency.EGP': 'الجنيه المصري',
    'currency.SAR': 'الريال السعودي',
    'currency.BHD': 'الدينار البحريني',
    'currency.OMR': 'الريال العماني',
    'currency.AED': 'الدرهم الإماراتي',
    'currency.ZAR': 'الراند الأفريقي',
    
    // Auth
    'auth.signIn': 'تسجيل الدخول',
    'auth.signOut': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.createAccount': 'إنشاء حساب',
    
    // Overview Dashboard
    'overview.title': 'لوحة المراقبة العامة',
    'overview.totalRevenue': 'إجمالي الإيرادات',
    'overview.activeProjects': 'المشاريع النشطة',
    'overview.pendingApprovals': 'الموافقات المعلقة',
    'overview.upcomingMilestones': 'المعالم القادمة',
    
    // Sales
    'sales.title': 'إدارة المبيعات',
    'sales.description': 'تتبع حجوزات الوحدات ومدفوعات العملاء وأداء المبيعات',
    'sales.newSale': 'مبيعة جديدة',
    'sales.addBooking': 'إضافة حجز',
    'sales.newBooking': 'حجز وحدة جديد',
    'sales.newBookingDescription': 'تسجيل حجز عميل جديد',
    'sales.unitNumber': 'رقم الوحدة',
    'sales.unitPlaceholder': 'مثال: أ-101',
    'sales.customerName': 'اسم العميل',
    'sales.customerPlaceholder': 'الاسم الكامل',
    'sales.emailPlaceholder': 'customer@email.com',
    'sales.phone': 'الهاتف',
    'sales.phonePlaceholder': '+966-555-0123',
    'sales.totalAmount': 'المبلغ الإجمالي',
    'sales.downPayment': 'الدفعة المقدمة',
    'sales.createBooking': 'إنشاء حجز',
    'sales.monthlyGrowth': '+15% من الشهر الماضي',
    'sales.unitsBooked': 'الوحدات المحجوزة',
    'sales.ofTotalUnits': 'من {{total}} وحدة إجمالية',
    'sales.commissionRate': '5% معدل العمولة',
    'sales.activeCustomers': 'العملاء النشطون',
    'sales.weeklyGrowth': '+3 هذا الأسبوع',
    'sales.progress': 'تقدم المبيعات',
    'sales.progressDescription': 'تقدم حجز الوحدات للمشروع الحالي',
    'sales.booked': 'محجوز',
    'sales.sold': 'مباع',
    'sales.available': 'متاح',
    'sales.records': 'سجلات المبيعات',
    'sales.recordsDescription': 'حجوزات العملاء وحالة الدفع',
    'sales.allStatus': 'جميع الحالات',
    'sales.pending': 'معلق',
    'sales.completed': 'مكتمل',
    'sales.unit': 'الوحدة',
    'sales.customer': 'العميل',
    'sales.contact': 'التواصل',
    'sales.agent': 'الوكيل',
    'sales.status': 'الحالة',
    'sales.date': 'التاريخ',
    'sales.totalSales': 'إجمالي المبيعات',
    'sales.pendingSales': 'المبيعات المعلقة',
    'sales.completedSales': 'المبيعات المكتملة',
    
    // Expenses
    'expenses.title': 'إدارة المصروفات',
    'expenses.description': 'تتبع واعتماد مصاريف المشروع بسير عمل شامل للفحص والاعتماد',
    'expenses.newExpense': 'مصروف جديد',
    'expenses.submitNewExpense': 'تقديم مصروف جديد',
    'expenses.submitDescription': 'تقديم مصروف جديد للاعتماد من خلال سير عمل الفحص والاعتماد',
    'expenses.totalApproved': 'إجمالي المعتمد',
    'expenses.expensesApproved': '{{count}} مصاريف معتمدة',
    'expenses.pendingApproval': 'في انتظار الموافقة',
    'expenses.awaitingReview': '{{count}} في انتظار المراجعة',
    'expenses.thisMonth': 'هذا الشهر',
    'expenses.monthlyChange': '5% مقارنة بالشهر الماضي',
    'expenses.requireResubmission': 'تتطلب إعادة تقديم',
    'expenses.approved': 'معتمد',
    'expenses.rejected': 'مرفوض',
    
    // Projects
    'projects.title': 'المشاريع',
    'projects.newProject': 'مشروع جديد',
    'projects.activeProjects': 'المشاريع النشطة',
    'projects.completedProjects': 'المشاريع المكتملة',

    // Bookings Dashboard
    'bookings.title': 'الحجوزات والمبيعات',
    'bookings.description': 'إدارة حجوزات الوحدات والمدفوعات وتتبع المبيعات',
    'bookings.recordPayment': 'تسجيل دفعة',
    'bookings.newBooking': 'حجز جديد',
    'bookings.allBookings': 'جميع الحجوزات',
    'bookings.installments': 'الأقساط',
    'bookings.payments': 'المدفوعات',
    'bookings.salesTargets': 'أهداف المبيعات',
    'bookings.unitBookings': 'حجوزات الوحدات',
    'bookings.unit': 'الوحدة',
    'bookings.customer': 'العميل',
    'bookings.amount': 'المبلغ',
    'bookings.bookingDate': 'تاريخ الحجز',
    'bookings.salesAgent': 'وكيل المبيعات',
    'bookings.status': 'الحالة',
    'bookings.actions': 'الإجراءات',
    'bookings.viewDetails': 'عرض التفاصيل',
    'bookings.discount': 'خصم',
    'bookings.newUnitBooking': 'حجز وحدة جديد',
    'bookings.newBookingDescription': 'إنشاء حجز جديد من خلال إدخال تفاصيل العميل واختيار وحدة وخطة الدفع.',
    'bookings.customerDetails': 'تفاصيل العميل',
    'bookings.unitSelection': 'اختيار الوحدة',
    'bookings.paymentPlan': 'خطة الدفع',
    'bookings.confirmation': 'التأكيد',
    'bookings.customerName': 'اسم العميل',
    'bookings.fullName': 'الاسم الكامل',
    'bookings.email': 'البريد الإلكتروني',
    'bookings.phoneNumber': 'رقم الهاتف',
    'bookings.address': 'العنوان',
    'bookings.completeAddress': 'العنوان الكامل',
    'bookings.unitType': 'نوع الوحدة',
    'bookings.selectUnitType': 'اختر نوع الوحدة',
    'bookings.availableUnits': 'الوحدات المتاحة',
    'bookings.selectUnit': 'اختر الوحدة',
    'bookings.area': 'المساحة (قدم مربع)',
    'bookings.ratePerSqFt': 'السعر لكل قدم مربع',
    'bookings.baseAmount': 'المبلغ الأساسي',
    'bookings.discountPercent': 'نسبة الخصم %',
    'bookings.selectPaymentPlan': 'اختر خطة الدفع',
    'bookings.standardPlan': 'الخطة القياسية - 24 شهر',
    'bookings.standardPlanDesc': '20% دفعة مقدمة، أقساط شهرية',
    'bookings.quickPlan': 'الدفع السريع - 12 شهر',
    'bookings.quickPlanDesc': '30% دفعة مقدمة، أقساط ربع سنوية',
    'bookings.booking': 'الحجز',
    'bookings.registration': 'التسجيل',
    'bookings.balance': 'الرصيد',
    'bookings.constructionLinked': 'مرتبط بالبناء',
    'bookings.bookingSummary': 'ملخص الحجز',
    'bookings.finalAmount': 'المبلغ النهائي',
    'bookings.bookingAmountDue': 'مبلغ الحجز المستحق',
    'bookings.confirmBooking': 'تأكيد الحجز',
    'bookings.bookingCreated': 'تم إنشاء الحجز بنجاح!',
    'bookings.recordPaymentTitle': 'تسجيل دفعة',
    'bookings.recordPaymentDesc': 'تسجيل دفعة مستلمة لقسط حجز معين مع تفاصيل المعاملة.',
    'bookings.bookingReference': 'مرجع الحجز',
    'bookings.selectBooking': 'اختر الحجز',
    'bookings.installment': 'القسط',
    'bookings.selectInstallment': 'اختر القسط',
    'bookings.paymentAmount': 'مبلغ الدفع',
    'bookings.amountReceived': 'المبلغ المستلم',
    'bookings.paymentMethod': 'طريقة الدفع',
    'bookings.selectMethod': 'اختر الطريقة',
    'bookings.cash': 'نقداً',
    'bookings.cheque': 'شيك',
    'bookings.bankTransfer': 'تحويل بنكي',
    'bookings.upi': 'UPI',
    'bookings.referenceNumber': 'الرقم المرجعي',
    'bookings.transactionNumber': 'رقم المعاملة/الشيك',
    'bookings.paymentDate': 'تاريخ الدفع',
    'bookings.recordPaymentSuccess': 'تم تسجيل الدفعة بنجاح!',
    'bookings.bookingDetails': 'تفاصيل الحجز',
    'bookings.bookingDetailsDesc': 'معلومات الحجز الكاملة وجدول الدفع',
    'bookings.customerInformation': 'معلومات العميل',
    'bookings.name': 'الاسم',
    'bookings.phone': 'الهاتف',
    'bookings.unitInformation': 'معلومات الوحدة',
    'bookings.type': 'النوع',
    'bookings.financialDetails': 'التفاصيل المالية',
    'bookings.totalAmount': 'المبلغ الإجمالي',
    'bookings.installmentSchedule': 'جدول الأقساط',
    'bookings.milestone': 'المعلم',
    'bookings.dueDate': 'تاريخ الاستحقاق',
    'bookings.close': 'إغلاق',
    'bookings.downloadAgreement': 'تحميل الاتفاقية',
    'bookings.agreementDownloaded': 'تم تحميل اتفاقية الحجز!',
    'bookings.booked': 'محجوز',
    'bookings.registered': 'مسجل',
    'bookings.cancelled': 'ملغي',
    'bookings.completed': 'مكتمل',
    'bookings.paid': 'مدفوع',
    'bookings.pending': 'معلق',
    'bookings.overdue': 'متأخر',

    // Commissions Dashboard
    'commissions.title': 'إدارة العمولات',
    'commissions.description': 'تتبع أداء الوكلاء ومدفوعات العمولات',
    'commissions.totalPaid': 'إجمالي المدفوع',
    'commissions.pending': 'معلق',
    'commissions.thisMonth': 'هذا الشهر',
    'commissions.averageRate': 'المعدل المتوسط',
    'commissions.payments': 'مدفوعات',
    'commissions.awaitingPayment': 'في انتظار الدفع',
    'commissions.monthlyGrowthPercent': '+22% من الشهر الماضي',
    'commissions.standardRate': 'معدل العمولة القياسي',
    'commissions.agentPerformance': 'أداء الوكلاء',
    'commissions.agentPerformanceDesc': 'أرباح العمولات حسب وكيل المبيعات',
    'commissions.unitsSold': 'الوحدات المباعة',
    'commissions.totalCommission': 'إجمالي العمولة',
    'commissions.performance': 'الأداء',
    'commissions.commissionRecords': 'سجلات العمولات',
    'commissions.commissionRecordsDesc': 'تتبع تفصيلي للعمولات وتاريخ المدفوعات',
    'commissions.agent': 'الوكيل',
    'commissions.saleDate': 'تاريخ البيع',
    'commissions.customer': 'العميل',
    'commissions.saleAmount': 'مبلغ البيع',
    'commissions.commission': 'العمولة',
    'commissions.paidDate': 'تاريخ الدفع',
    'commissions.processPayment': 'معالجة الدفع',

    // Overview Dashboard - Additional Keys
    'overview.welcomeBack': 'مرحباً بعودتك، {{name}}. إليك ما يحدث مع مشاريعك.',
    'overview.totalInvestment': 'إجمالي الاستثمار',
    'overview.currentCashBalance': 'الرصيد النقدي الحالي',
    'overview.totalExpenses': 'إجمالي المصروفات',
    'overview.projectRevenue': 'إيرادات المشروع',
    'overview.budgetRemaining': 'الميزانية المتبقية',
    'overview.monthlyExpenses': 'المصروفات الشهرية',
    'overview.cashAvailable': 'النقد المتاح',
    'overview.unitsBooked': 'الوحدات المحجوزة',
    'overview.monthlySales': 'المبيعات الشهرية',
    'overview.commissionEarned': 'العمولة المكتسبة',
    'overview.activeCustomers': 'العملاء النشطون',
    'overview.totalBudget': 'إجمالي الميزانية',
    'overview.cashBalance': 'الرصيد النقدي',
    'overview.netRevenue': 'صافي الإيرادات',
    'overview.budgetUtilization': 'استخدام الميزانية',
    'overview.budgetUsed': '{{used}} من {{total}} مستخدم',
    'overview.salesProgress': 'تقدم المبيعات',
    'overview.unitsBookedOf': '{{booked}} من {{total}} وحدة محجوزة',
    'overview.recentActivity': 'النشاط الأخير',
    'overview.recentActivityDesc': 'آخر التحديثات من مشاريعك',
    'overview.newUnitBooking': 'حجز وحدة جديد',
    'overview.unitBookedBy': 'الوحدة {{unit}} محجوزة من قبل {{customer}}',
    'overview.expenseApprovalPending': 'موافقة المصروفات معلقة',
    'overview.constructionMaterials': 'مواد البناء - {{amount}}',
    'overview.paymentReceived': 'تم استلام الدفعة',
    'overview.installmentPayment': 'دفعة قسط من {{customer}}',
    'overview.budgetMilestone': 'تم الوصول لمعلم الميزانية',
    'overview.budgetUtilized': '{{percent}}% من ميزانية البناء مستخدمة',
    'overview.hoursAgo': 'منذ {{hours}} ساعات',
    'overview.dayAgo': 'منذ {{days}} يوم',
    'overview.allocated': 'مخصص',
    'overview.available': 'متاح',
    'overview.waiting': '{{count}} في الانتظار',
    'overview.units': 'وحدات',
    'overview.thisWeek': '+{{count}} هذا الأسبوع',

    // User Management Dashboard
    'userManagement.title': 'إدارة المستخدمين',
    'userManagement.description': 'إدارة حسابات المستخدمين والصلاحيات وإعدادات المؤسسة',
    'userManagement.inviteUser': 'دعوة مستخدم',
    'userManagement.activeUsers': 'المستخدمون النشطون',
    'userManagement.pendingInvitations': 'الدعوات المعلقة',
    'userManagement.totalUsers': 'إجمالي المستخدمين',
    'userManagement.newThisMonth': 'جديد هذا الشهر',
    'userManagement.userGrowth': '+{{percent}}% نمو المستخدمين',
    'userManagement.invitationsSent': '{{count}} دعوات مرسلة',
    'userManagement.userDetails': 'تفاصيل المستخدم',
    'userManagement.role': 'الدور',
    'userManagement.lastActive': 'آخر نشاط',
    'userManagement.joinDate': 'تاريخ الانضمام',
    'userManagement.editUser': 'تعديل المستخدم',
    'userManagement.deleteUser': 'حذف المستخدم',
    'userManagement.invitationStatus': 'حالة الدعوة',
    'userManagement.sentDate': 'تاريخ الإرسال',
    'userManagement.resendInvitation': 'إعادة إرسال الدعوة',
    'userManagement.cancelInvitation': 'إلغاء الدعوة',

    // Material Management Dashboard
    'materials.title': 'إدارة المواد',
    'materials.description': 'تتبع مخزون المواد والاستخدام ومتطلبات الشراء',
    'materials.addMaterial': 'إضافة مادة',
    'materials.createPO': 'إنشاء أمر شراء',
    'materials.totalMaterials': 'إجمالي المواد',
    'materials.categoriesManaged': 'فئات مُدارة',
    'materials.lowStock': 'مخزون منخفض',
    'materials.itemsNeedReorder': 'عناصر تحتاج إعادة طلب',
    'materials.thisMonth': 'هذا الشهر',
    'materials.consumed': 'مستهلك',
    'materials.materialsUsed': 'مواد مستخدمة',
    'materials.categories': 'الفئات',
    'materials.category': 'الفئة',
    'materials.quantity': 'الكمية',
    'materials.unit': 'الوحدة',
    'materials.unitCost': 'تكلفة الوحدة',
    'materials.totalValue': 'القيمة الإجمالية',
    'materials.supplier': 'المورد',
    'materials.lastUpdated': 'آخر تحديث',
    'materials.stockLevel': 'مستوى المخزون',
    'materials.reorderLevel': 'مستوى إعادة الطلب',
    'materials.viewDetails': 'عرض التفاصيل',

    // Vendor Management Dashboard
    'vendors.title': 'إدارة الموردين',
    'vendors.description': 'إدارة علاقات الموردين والعقود وتتبع الأداء',
    'vendors.addVendor': 'إضافة مورد',
    'vendors.totalVendors': 'إجمالي الموردين',
    'vendors.activeContracts': 'العقود النشطة',
    'vendors.pendingPayments': 'المدفوعات المعلقة',
    'vendors.averageRating': 'التقييم المتوسط',
    'vendors.ratingOutOf5': 'من 5 نجوم',
    'vendors.activeVendors': 'الموردون النشطون',
    'vendors.vendorName': 'اسم المورد',
    'vendors.contactPerson': 'شخص الاتصال',
    'vendors.phone': 'الهاتف',
    'vendors.email': 'البريد الإلكتروني',
    'vendors.services': 'الخدمات',
    'vendors.rating': 'التقييم',
    'vendors.status': 'الحالة',
    'vendors.actions': 'الإجراءات',
    'vendors.edit': 'تعديل',
    'vendors.viewContracts': 'عرض العقود',

    // Procurement Dashboard
    'procurement.title': 'إدارة المشتريات',
    'procurement.description': 'إدارة طلبات الشراء والموافقات واختيار الموردين',
    'procurement.newRequest': 'طلب جديد',
    'procurement.totalRequests': 'إجمالي الطلبات',
    'procurement.awaitingApproval': 'في انتظار الموافقة',
    'procurement.approvedValue': 'القيمة المعتمدة',
    'procurement.thisMonth': 'هذا الشهر',
    'procurement.processed': 'معالج',
    'procurement.requestsProcessed': 'طلبات معالجة',
    'procurement.procurementRequests': 'طلبات الشراء',
    'procurement.requestId': 'معرف الطلب',
    'procurement.requestedBy': 'طلب من قبل',
    'procurement.amount': 'المبلغ',
    'procurement.status': 'الحالة',
    'procurement.requestDate': 'تاريخ الطلب',
    'procurement.actions': 'الإجراءات',
    'procurement.approve': 'موافقة',
    'procurement.reject': 'رفض',
    'procurement.review': 'مراجعة',

    // Purchase Orders Dashboard
    'purchaseOrders.title': 'أوامر الشراء',
    'purchaseOrders.description': 'إنشاء وإدارة أوامر الشراء للمواد والخدمات',
    'purchaseOrders.createPO': 'إنشاء أمر شراء',
    'purchaseOrders.totalPOs': 'إجمالي الأوامر',
    'purchaseOrders.awaitingDelivery': 'في انتظار التسليم',
    'purchaseOrders.totalValue': 'القيمة الإجمالية',
    'purchaseOrders.thisMonth': 'هذا الشهر',
    'purchaseOrders.created': 'مُنشأ',
    'purchaseOrders.poNumber': 'رقم الأمر',
    'purchaseOrders.vendor': 'المورد',
    'purchaseOrders.items': 'العناصر',
    'purchaseOrders.amount': 'المبلغ',
    'purchaseOrders.status': 'الحالة',
    'purchaseOrders.orderDate': 'تاريخ الطلب',
    'purchaseOrders.expectedDelivery': 'التسليم المتوقع',
    'purchaseOrders.actions': 'الإجراءات',
    'purchaseOrders.viewPO': 'عرض الأمر',

    // Reports Dashboard
    'reports.title': 'التقارير والتحليلات',
    'reports.description': 'إنشاء تقارير وتحليلات شاملة لرؤى المشروع',
    'reports.generateReport': 'إنشاء تقرير',
    'reports.financialReports': 'التقارير المالية',
    'reports.salesReports': 'تقارير المبيعات',
    'reports.expenseReports': 'تقارير المصروفات',
    'reports.projectReports': 'تقارير المشاريع',
    'reports.exportPDF': 'تصدير PDF',
    'reports.exportExcel': 'تصدير Excel',
    'reports.dateRange': 'نطاق التاريخ',
    'reports.selectRange': 'اختر نطاق التاريخ',
    'reports.reportType': 'نوع التقرير',
    'reports.selectType': 'اختر نوع التقرير',

    // Project Setup Dashboard
    'projectSetup.title': 'إعداد المشروع',
    'projectSetup.description': 'تكوين مشاريع جديدة بالمعلومات الأساسية والميزانيات والمعالم',
    'projectSetup.newProject': 'مشروع جديد',
    'projectSetup.activeProjects': 'المشاريع النشطة',
    'projectSetup.completedProjects': 'المشاريع المكتملة',
    'projectSetup.totalBudget': 'إجمالي الميزانية',
    'projectSetup.projectName': 'اسم المشروع',
    'projectSetup.location': 'الموقع',
    'projectSetup.startDate': 'تاريخ البدء',
    'projectSetup.expectedCompletion': 'الإنجاز المتوقع',
    'projectSetup.status': 'الحالة',
    'projectSetup.progress': 'التقدم',
    'projectSetup.actions': 'الإجراءات',
    'projectSetup.viewProject': 'عرض المشروع',
    'projectSetup.editProject': 'تعديل المشروع',

    // Project Milestones Dashboard
    'milestones.title': 'معالم المشروع',
    'milestones.description': 'تتبع تقدم المشروع من خلال المعالم الرئيسية والمخرجات',
    'milestones.addMilestone': 'إضافة معلم',
    'milestones.totalMilestones': 'إجمالي المعالم',
    'milestones.completed': 'مكتمل',
    'milestones.inProgress': 'قيد التنفيذ',
    'milestones.upcoming': 'قادم',
    'milestones.milestoneName': 'اسم المعلم',
    'milestones.project': 'المشروع',
    'milestones.targetDate': 'التاريخ المستهدف',
    'milestones.actualDate': 'التاريخ الفعلي',
    'milestones.status': 'الحالة',
    'milestones.progress': 'التقدم',
    'milestones.actions': 'الإجراءات',
    'milestones.markComplete': 'وضع علامة مكتمل',
    'milestones.updateProgress': 'تحديث التقدم',

    // Employee Management Dashboard
    'employees.title': 'إدارة الموظفين',
    'employees.description': 'إدارة سجلات الموظفين والحضور وتتبع الأداء',
    'employees.addEmployee': 'إضافة موظف',
    'employees.totalEmployees': 'إجمالي الموظفين',
    'employees.activeEmployees': 'الموظفون النشطون',
    'employees.onLeave': 'في إجازة',
    'employees.newHires': 'موظفون جدد',
    'employees.employeeName': 'اسم الموظف',
    'employees.department': 'القسم',
    'employees.position': 'المنصب',
    'employees.joinDate': 'تاريخ الالتحاق',
    'employees.phone': 'الهاتف',
    'employees.email': 'البريد الإلكتروني',
    'employees.status': 'الحالة',
    'employees.actions': 'الإجراءات',
    'employees.viewProfile': 'عرض الملف الشخصي',
    'employees.editEmployee': 'تعديل الموظف',

    // Marketing Communication Dashboard
    'marketing.title': 'التسويق والاتصالات',
    'marketing.description': 'إدارة حملات التسويق وتواصل العملاء وتوليد العملاء المحتملين',
    'marketing.newCampaign': 'حملة جديدة',
    'marketing.activeCampaigns': 'الحملات النشطة',
    'marketing.totalLeads': 'إجمالي العملاء المحتملين',
    'marketing.conversionRate': 'معدل التحويل',
    'marketing.campaignROI': 'عائد الاستثمار للحملة',
    'marketing.campaignName': 'اسم الحملة',
    'marketing.type': 'النوع',
    'marketing.startDate': 'تاريخ البدء',
    'marketing.endDate': 'تاريخ الانتهاء',
    'marketing.budget': 'الميزانية',
    'marketing.spent': 'منفق',
    'marketing.leads': 'عملاء محتملون',
    'marketing.conversions': 'تحويلات',
    'marketing.actions': 'الإجراءات',
    'marketing.viewCampaign': 'عرض الحملة',
    'marketing.editCampaign': 'تعديل الحملة',

    // Account Statements Dashboard
    'accountStatements.title': 'كشوف الحسابات',
    'accountStatements.description': 'عرض وإدارة كشوف الحسابات المالية وتاريخ المعاملات',
    'accountStatements.generateStatement': 'إنشاء كشف',
    'accountStatements.accountBalance': 'رصيد الحساب',
    'accountStatements.monthlyInflow': 'التدفق الداخل الشهري',
    'accountStatements.monthlyOutflow': 'التدفق الخارج الشهري',
    'accountStatements.pendingTransactions': 'المعاملات المعلقة',
    'accountStatements.transactionHistory': 'تاريخ المعاملات',
    'accountStatements.date': 'التاريخ',
    'accountStatements.type': 'النوع',
    'accountStatements.amount': 'المبلغ',
    'accountStatements.balance': 'الرصيد',
    'accountStatements.reference': 'المرجع',
    'accountStatements.status': 'الحالة',

    // Auto Invoice System Dashboard
    'autoInvoice.title': 'نظام الفواتير التلقائي',
    'autoInvoice.description': 'إنشاء وإدارة الفواتير التلقائية للفوترة القائمة على المعالم',
    'autoInvoice.createInvoice': 'إنشاء فاتورة',
    'autoInvoice.totalInvoices': 'إجمالي الفواتير',
    'autoInvoice.pendingInvoices': 'الفواتير المعلقة',
    'autoInvoice.paidInvoices': 'الفواتير المدفوعة',
    'autoInvoice.overdueInvoices': 'الفواتير المتأخرة',
    'autoInvoice.invoiceNumber': 'رقم الفاتورة',
    'autoInvoice.customer': 'العميل',
    'autoInvoice.amount': 'المبلغ',
    'autoInvoice.issueDate': 'تاريخ الإصدار',
    'autoInvoice.dueDate': 'تاريخ الاستحقاق',
    'autoInvoice.status': 'الحالة',
    'autoInvoice.actions': 'الإجراءات',
    'autoInvoice.viewInvoice': 'عرض الفاتورة',
    'autoInvoice.sendReminder': 'إرسال تذكير',

    // Installments Invoicing Dashboard
    'installments.title': 'الأقساط والفوترة',
    'installments.description': 'إدارة جداول الأقساط وإنشاء الفواتير التلقائية',
    'installments.generateInvoices': 'إنشاء فواتير',
    'installments.totalInstallments': 'إجمالي الأقساط',
    'installments.dueThisMonth': 'مستحق هذا الشهر',
    'installments.overdue': 'متأخر',
    'installments.collected': 'محصل',
    'installments.installmentSchedule': 'جدول الأقساط',
    'installments.customer': 'العميل',
    'installments.unit': 'الوحدة',
    'installments.milestone': 'المعلم',
    'installments.amount': 'المبلغ',
    'installments.dueDate': 'تاريخ الاستحقاق',
    'installments.status': 'الحالة',
    'installments.actions': 'الإجراءات',
    'installments.generateInvoice': 'إنشاء فاتورة',
    'installments.recordPayment': 'تسجيل دفعة'
  },
  
  ur: {
    // Navigation & Common
    'common.save': 'محفوظ کریں',
    'common.cancel': 'منسوخ کریں',
    'common.confirm': 'تصدیق کریں',
    'common.delete': 'حذف کریں',
    'common.edit': 'ترمیم کریں',
    'common.add': 'شامل کریں',
    'common.search': 'تلاش کریں',
    'common.loading': 'لوڈ ہو رہا ہے...',
    'common.error': 'خرابی',
    'common.success': 'کامیاب',
    'common.warning': 'انتباہ',
    'common.info': 'معلومات',
    
    // Dashboard Navigation
    'nav.overview': 'جائزہ',
    'nav.sales': 'فروخت',
    'nav.bookings': 'بکنگز',
    'nav.expenses': 'اخراجات',
    'nav.commissions': 'کمیشن',
    'nav.reports': 'رپورٹس',
    'nav.settings': 'سیٹنگز',
    'nav.userManagement': 'صارف کا انتظام',
    'nav.vendorManagement': 'فراہم کنندہ کا انتظام',
    'nav.materialManagement': 'مواد کا انتظام',
    'nav.procurement': 'خریداری',
    'nav.purchaseOrders': 'خرید کے احکامات',
    'nav.projectMilestones': 'پروجیکٹ کے سنگ میل',
    
    // Settings
    'settings.title': 'تنظیم کی سیٹنگز',
    'settings.description': 'اپنی برانڈنگ، تھیمز اور ٹیمپلیٹس کو حسب ضرورت بنائیں',
    'settings.language': 'زبان',
    'settings.currency': 'کرنسی',
    'settings.languageDescription': 'اپنی پسندیدہ زبان منتخب کریں',
    'settings.currencyDescription': 'اپنی تنظیم کی ڈیفالٹ کرنسی منتخب کریں',
    'settings.saveChanges': 'تبدیلیاں محفوظ کریں',
    'settings.localization': 'مقامیانہ',
    'settings.localizationDescription': 'زبان اور علاقائی سیٹنگز',
    
    // Currency Names
    'currency.USD': 'امریکی ڈالر',
    'currency.PKR': 'پاکستانی روپیہ',
    'currency.EGP': 'مصری پاؤنڈ',
    'currency.SAR': 'سعودی ریال',
    'currency.BHD': 'بحرینی دینار',
    'currency.OMR': 'عمانی ریال',
    'currency.AED': 'اماراتی درہم',
    'currency.ZAR': 'جنوبی افریقی رینڈ',
    
    // Auth
    'auth.signIn': 'سائن ان کریں',
    'auth.signOut': 'سائن آؤٹ کریں',
    'auth.email': 'ای میل',
    'auth.password': 'پاس ورڈ',
    'auth.forgotPassword': 'پاس ورڈ بھول گئے؟',
    'auth.createAccount': 'اکاؤنٹ بنائیں',
    
    // Overview Dashboard
    'overview.title': 'ڈیش بورڈ جائزہ',
    'overview.totalRevenue': 'کل آمدنی',
    'overview.activeProjects': 'فعال پروجیکٹس',
    'overview.pendingApprovals': 'زیر التواء منظوریاں',
    'overview.upcomingMilestones': 'آنے والے سنگ میل',
    
    // Sales
    'sales.title': 'فروخت کا انتظام',
    'sales.description': 'یونٹ بکنگز، کسٹمر پیمنٹس، اور فروخت کی کارکردگی کو ٹریک کریں',
    'sales.newSale': 'نئی فروخت',
    'sales.addBooking': 'بکنگ شامل کریں',
    'sales.newBooking': 'نئی یونٹ بکنگ',
    'sales.newBookingDescription': 'نئے کسٹمر کی بکنگ ریکارڈ کریں',
    'sales.unitNumber': 'یونٹ نمبر',
    'sales.unitPlaceholder': 'مثال: A-101',
    'sales.customerName': 'کسٹمر کا نام',
    'sales.customerPlaceholder': 'مکمل نام',
    'sales.emailPlaceholder': 'customer@email.com',
    'sales.phone': 'فون',
    'sales.phonePlaceholder': '+92-300-0123456',
    'sales.totalAmount': 'کل رقم',
    'sales.downPayment': 'پیشگی ادائیگی',
    'sales.createBooking': 'بکنگ بنائیں',
    'sales.monthlyGrowth': 'گزشتہ ماہ سے +15%',
    'sales.unitsBooked': 'بک شدہ یونٹس',
    'sales.ofTotalUnits': 'کل {{total}} یونٹس میں سے',
    'sales.commissionRate': '5% کمیشن کی شرح',
    'sales.activeCustomers': 'فعال کسٹمرز',
    'sales.weeklyGrowth': 'اس ہفتے +3',
    'sales.progress': 'فروخت کی پیشرفت',
    'sales.progressDescription': 'موجودہ پروجیکٹ کے لیے یونٹ بکنگ کی پیشرفت',
    'sales.booked': 'بک شدہ',
    'sales.sold': 'فروخت شدہ',
    'sales.available': 'دستیاب',
    'sales.records': 'فروخت کے ریکارڈ',
    'sales.recordsDescription': 'کسٹمر بکنگز اور ادائیگی کی صورتحال',
    'sales.allStatus': 'تمام حالات',
    'sales.pending': 'زیر التواء',
    'sales.completed': 'مکمل',
    'sales.unit': 'یونٹ',
    'sales.customer': 'کسٹمر',
    'sales.contact': 'رابطہ',
    'sales.agent': 'ایجنٹ',
    'sales.status': 'حالت',
    'sales.date': 'تاریخ',
    'sales.totalSales': 'کل فروخت',
    'sales.pendingSales': 'زیر التواء فروخت',
    'sales.completedSales': 'مکمل شدہ فروخت',
    
    // Expenses
    'expenses.title': 'اخراجات کا انتظام',
    'expenses.description': 'میکر-چیکر ورک فلو کے ساتھ پروجیکٹ کے اخراجات کو ٹریک اور منظور کریں',
    'expenses.newExpense': 'نیا خرچہ',
    'expenses.submitNewExpense': 'نیا خرچہ جمع کریں',
    'expenses.submitDescription': 'میکر-چیکر ورک فلو کے ذریعے منظوری کے لیے نیا خرچہ جمع کریں',
    'expenses.totalApproved': 'کل منظور شدہ',
    'expenses.expensesApproved': '{{count}} اخراجات منظور شدہ',
    'expenses.pendingApproval': 'منظوری کا انتظار',
    'expenses.awaitingReview': '{{count}} جائزے کا انتظار',
    'expenses.thisMonth': 'اس مہینے',
    'expenses.monthlyChange': 'پچھلے مہینے کے مقابلے میں 5%',
    'expenses.requireResubmission': 'دوبارہ جمع کرنے کی ضرورت',
    'expenses.approved': 'منظور شدہ',
    'expenses.rejected': 'مسترد',
    
    // Projects
    'projects.title': 'پروجیکٹس',
    'projects.newProject': 'نیا پروجیکٹ',
    'projects.activeProjects': 'فعال پروجیکٹس',
    'projects.completedProjects': 'مکمل پروجیکٹس',

    // Bookings Dashboard
    'bookings.title': 'بکنگز اور سیلز',
    'bookings.description': 'یونٹ بکنگز، پیمنٹس، اور سیلز ٹریکنگ کا انتظام',
    'bookings.recordPayment': 'پیمنٹ ریکارڈ کریں',
    'bookings.newBooking': 'نئی بکنگ',
    'bookings.allBookings': 'تمام بکنگز',
    'bookings.installments': 'قسطیں',
    'bookings.payments': 'پیمنٹس',
    'bookings.salesTargets': 'سیلز ٹارگٹس',
    'bookings.unitBookings': 'یونٹ بکنگز',
    'bookings.unit': 'یونٹ',
    'bookings.customer': 'کسٹمر',
    'bookings.amount': 'رقم',
    'bookings.bookingDate': 'بکنگ کی تاریخ',
    'bookings.salesAgent': 'سیلز ایجنٹ',
    'bookings.status': 'حالت',
    'bookings.actions': 'اعمال',
    'bookings.viewDetails': 'تفصیلات دیکھیں',
    'bookings.discount': 'رعایت',
    'bookings.newUnitBooking': 'نئی یونٹ بکنگ',
    'bookings.newBookingDescription': 'کسٹمر کی تفصیلات داخل کرکے، یونٹ منتخب کرکے، اور پیمنٹ پلان چن کر نئی بکنگ بنائیں۔',
    'bookings.customerDetails': 'کسٹمر کی تفصیلات',
    'bookings.unitSelection': 'یونٹ کا انتخاب',
    'bookings.paymentPlan': 'پیمنٹ پلان',
    'bookings.confirmation': 'تصدیق',
    'bookings.customerName': 'کسٹمر کا نام',
    'bookings.fullName': 'مکمل نام',
    'bookings.email': 'ای میل',
    'bookings.phoneNumber': 'فون نمبر',
    'bookings.address': 'پتہ',
    'bookings.completeAddress': 'مکمل پتہ',
    'bookings.unitType': 'یونٹ کی قسم',
    'bookings.selectUnitType': 'یونٹ کی قسم منتخب کریں',
    'bookings.availableUnits': 'دستیاب یونٹس',
    'bookings.selectUnit': 'یونٹ منتخب کریں',
    'bookings.area': 'رقبہ (مربع فٹ)',
    'bookings.ratePerSqFt': 'فی مربع فٹ ریٹ',
    'bookings.baseAmount': 'بنیادی رقم',
    'bookings.discountPercent': 'رعایت %',
    'bookings.selectPaymentPlan': 'پیمنٹ پلان منتخب کریں',
    'bookings.standardPlan': 'معیاری پلان - 24 ماہ',
    'bookings.standardPlanDesc': '20% پیشگی ادائیگی، ماہانہ قسطیں',
    'bookings.quickPlan': 'فوری ادائیگی - 12 ماہ',
    'bookings.quickPlanDesc': '30% پیشگی ادائیگی، سہ ماہی قسطیں',
    'bookings.booking': 'بکنگ',
    'bookings.registration': 'رجسٹریشن',
    'bookings.balance': 'بیلنس',
    'bookings.constructionLinked': 'تعمیر سے منسلک',
    'bookings.bookingSummary': 'بکنگ کا خلاصہ',
    'bookings.finalAmount': 'حتمی رقم',
    'bookings.bookingAmountDue': 'بکنگ کی واجب الادا رقم',
    'bookings.confirmBooking': 'بکنگ کی تصدیق کریں',
    'bookings.bookingCreated': 'بکنگ کامیابی سے بن گئی!',
    'bookings.recordPaymentTitle': 'پیمنٹ ریکارڈ کریں',
    'bookings.recordPaymentDesc': 'کسی مخصوص بکنگ قسط کے لیے موصولہ پیمنٹ کو ٹرانزیکشن کی تفصیلات کے ساتھ ریکارڈ کریں۔',
    'bookings.bookingReference': 'بکنگ ریفرنس',
    'bookings.selectBooking': 'بکنگ منتخب کریں',
    'bookings.installment': 'قسط',
    'bookings.selectInstallment': 'قسط منتخب کریں',
    'bookings.paymentAmount': 'پیمنٹ کی رقم',
    'bookings.amountReceived': 'موصولہ رقم',
    'bookings.paymentMethod': 'پیمنٹ کا طریقہ',
    'bookings.selectMethod': 'طریقہ منتخب کریں',
    'bookings.cash': 'نقد',
    'bookings.cheque': 'چیک',
    'bookings.bankTransfer': 'بینک ٹرانسفر',
    'bookings.upi': 'UPI',
    'bookings.referenceNumber': 'ریفرنس نمبر',
    'bookings.transactionNumber': 'ٹرانزیکشن/چیک نمبر',
    'bookings.paymentDate': 'پیمنٹ کی تاریخ',
    'bookings.recordPaymentSuccess': 'پیمنٹ کامیابی سے ریکارڈ ہو گئی!',
    'bookings.bookingDetails': 'بکنگ کی تفصیلات',
    'bookings.bookingDetailsDesc': 'مکمل بکنگ کی معلومات اور پیمنٹ شیڈول',
    'bookings.customerInformation': 'کسٹمر کی معلومات',
    'bookings.name': 'نام',
    'bookings.phone': 'فون',
    'bookings.unitInformation': 'یونٹ کی معلومات',
    'bookings.type': 'قسم',
    'bookings.financialDetails': 'مالی تفصیلات',
    'bookings.totalAmount': 'کل رقم',
    'bookings.installmentSchedule': 'قسطوں کا شیڈول',
    'bookings.milestone': 'سنگ میل',
    'bookings.dueDate': 'واجبی تاریخ',
    'bookings.close': 'بند کریں',
    'bookings.downloadAgreement': 'معاہدہ ڈاؤن لوڈ کریں',
    'bookings.agreementDownloaded': 'بکنگ کا معاہدہ ڈاؤن لوڈ ہو گیا!',
    'bookings.booked': 'بک شدہ',
    'bookings.registered': 'رجسٹرڈ',
    'bookings.cancelled': 'منسوخ',
    'bookings.completed': 'مکمل',
    'bookings.paid': 'ادا شدہ',
    'bookings.pending': 'زیر التواء',
    'bookings.overdue': 'مقررہ وقت گزر چکا',

    // Commissions Dashboard
    'commissions.title': 'کمیشن کا انتظام',
    'commissions.description': 'ایجنٹ کی کارکردگی اور کمیشن کی ادائیگیوں کو ٹریک کریں',
    'commissions.totalPaid': 'کل ادا شدہ',
    'commissions.pending': 'زیر التواء',
    'commissions.thisMonth': 'اس مہینے',
    'commissions.averageRate': 'اوسط ریٹ',
    'commissions.payments': 'ادائیگیاں',
    'commissions.awaitingPayment': 'ادائیگی کا انتظار',
    'commissions.monthlyGrowthPercent': 'پچھلے مہینے سے +22%',
    'commissions.standardRate': 'معیاری کمیشن ریٹ',
    'commissions.agentPerformance': 'ایجنٹ کی کارکردگی',
    'commissions.agentPerformanceDesc': 'سیلز ایجنٹ کے حساب سے کمیشن کی آمدنی',
    'commissions.unitsSold': 'فروخت شدہ یونٹس',
    'commissions.totalCommission': 'کل کمیشن',
    'commissions.performance': 'کارکردگی',
    'commissions.commissionRecords': 'کمیشن کے ریکارڈز',
    'commissions.commissionRecordsDesc': 'کمیشن کی تفصیلی ٹریکنگ اور ادائیگی کی تاریخ',
    'commissions.agent': 'ایجنٹ',
    'commissions.saleDate': 'فروخت کی تاریخ',
    'commissions.customer': 'کسٹمر',
    'commissions.saleAmount': 'فروخت کی رقم',
    'commissions.commission': 'کمیشن',
    'commissions.paidDate': 'ادائیگی کی تاریخ',
    'commissions.processPayment': 'ادائیگی پروسیس کریں',

    // Overview Dashboard - Additional Keys
    'overview.welcomeBack': 'واپسی مبارک، {{name}}۔ یہاں آپ کے پروجیکٹس کے ساتھ کیا ہو رہا ہے۔',
    'overview.totalInvestment': 'کل سرمایہ کاری',
    'overview.currentCashBalance': 'موجودہ نقد بیلنس',
    'overview.totalExpenses': 'کل اخراجات',
    'overview.projectRevenue': 'پروجیکٹ کی آمدنی',
    'overview.budgetRemaining': 'باقی بجٹ',
    'overview.monthlyExpenses': 'ماہانہ اخراجات',
    'overview.cashAvailable': 'دستیاب نقد',
    'overview.unitsBooked': 'بک شدہ یونٹس',
    'overview.monthlySales': 'ماہانہ فروخت',
    'overview.commissionEarned': 'حاصل شدہ کمیشن',
    'overview.activeCustomers': 'فعال کسٹمرز',
    'overview.totalBudget': 'کل بجٹ',
    'overview.cashBalance': 'نقد بیلنس',
    'overview.netRevenue': 'خالص آمدنی',
    'overview.budgetUtilization': 'بجٹ کا استعمال',
    'overview.budgetUsed': '{{total}} میں سے {{used}} استعمال شدہ',
    'overview.salesProgress': 'فروخت کی پیشرفت',
    'overview.unitsBookedOf': '{{total}} یونٹس میں سے {{booked}} بک شدہ',
    'overview.recentActivity': 'حالیہ سرگرمی',
    'overview.recentActivityDesc': 'آپ کے پروجیکٹس سے تازہ اپڈیٹس',
    'overview.newUnitBooking': 'نئی یونٹ بکنگ',
    'overview.unitBookedBy': 'یونٹ {{unit}} {{customer}} نے بک کیا',
    'overview.expenseApprovalPending': 'خرچے کی منظوری زیر التواء',
    'overview.constructionMaterials': 'تعمیراتی مواد - {{amount}}',
    'overview.paymentReceived': 'ادائیگی موصول ہوئی',
    'overview.installmentPayment': '{{customer}} سے قسط کی ادائیگی',
    'overview.budgetMilestone': 'بجٹ کے سنگ میل تک پہنچ گئے',
    'overview.budgetUtilized': 'تعمیراتی بجٹ کا {{percent}}% استعمال ہوا',
    'overview.hoursAgo': '{{hours}} گھنٹے پہلے',
    'overview.dayAgo': '{{days}} دن پہلے',
    'overview.allocated': 'مختص',
    'overview.available': 'دستیاب',
    'overview.waiting': '{{count}} انتظار میں',
    'overview.units': 'یونٹس',
    'overview.thisWeek': 'اس ہفتے +{{count}}',

    // User Management Dashboard
    'userManagement.title': 'صارف کا انتظام',
    'userManagement.description': 'صارف اکاؤنٹس، اجازات، اور تنظیمی سیٹنگز کا انتظام',
    'userManagement.inviteUser': 'صارف کو دعوت دیں',
    'userManagement.activeUsers': 'فعال صارفین',
    'userManagement.pendingInvitations': 'زیر التواء دعوات',
    'userManagement.totalUsers': 'کل صارفین',
    'userManagement.newThisMonth': 'اس مہینے نئے',
    'userManagement.userGrowth': '+{{percent}}% صارف اضافہ',
    'userManagement.invitationsSent': '{{count}} دعوات بھیجی گئیں',
    'userManagement.userDetails': 'صارف کی تفصیلات',
    'userManagement.role': 'کردار',
    'userManagement.lastActive': 'آخری بار فعال',
    'userManagement.joinDate': 'شمولیت کی تاریخ',
    'userManagement.editUser': 'صارف میں ترمیم',
    'userManagement.deleteUser': 'صارف کو حذف کریں',
    'userManagement.invitationStatus': 'دعوت کی حالت',
    'userManagement.sentDate': 'بھیجنے کی تاریخ',
    'userManagement.resendInvitation': 'دعوت دوبارہ بھیجیں',
    'userManagement.cancelInvitation': 'دعوت منسوخ کریں',

    // Material Management Dashboard
    'materials.title': 'مواد کا انتظام',
    'materials.description': 'مواد کی انوینٹری، استعمال، اور خریداری کی ضروریات کو ٹریک کریں',
    'materials.addMaterial': 'مواد شامل کریں',
    'materials.createPO': 'PO بنائیں',
    'materials.totalMaterials': 'کل مواد',
    'materials.categoriesManaged': 'زمرے منظوری شدہ',
    'materials.lowStock': 'کم اسٹاک',
    'materials.itemsNeedReorder': 'اشیاء کو دوبارہ آرڈر کرنا ہے',
    'materials.thisMonth': 'اس مہینے',
    'materials.consumed': 'استعمال شدہ',
    'materials.materialsUsed': 'مواد استعمال شدہ',
    'materials.categories': 'زمرے',
    'materials.category': 'زمرہ',
    'materials.quantity': 'مقدار',
    'materials.unit': 'یونٹ',
    'materials.unitCost': 'یونٹ کی لاگت',
    'materials.totalValue': 'کل قیمت',
    'materials.supplier': 'سپلائر',
    'materials.lastUpdated': 'آخری بار اپڈیٹ',
    'materials.stockLevel': 'اسٹاک کی سطح',
    'materials.reorderLevel': 'دوبارہ آرڈر کی سطح',
    'materials.viewDetails': 'تفصیلات دیکھیں',

    // Vendor Management Dashboard
    'vendors.title': 'وینڈر کا انتظام',
    'vendors.description': 'وینڈر کے تعلقات، معاہدات، اور کارکردگی کی ٹریکنگ کا انتظام',
    'vendors.addVendor': 'وینڈر شامل کریں',
    'vendors.totalVendors': 'کل وینڈرز',
    'vendors.activeContracts': 'فعال معاہدات',
    'vendors.pendingPayments': 'زیر التواء ادائیگیاں',
    'vendors.averageRating': 'اوسط درجہ بندی',
    'vendors.ratingOutOf5': '5 ستاروں میں سے',
    'vendors.activeVendors': 'فعال وینڈرز',
    'vendors.vendorName': 'وینڈر کا نام',
    'vendors.contactPerson': 'رابطہ کار',
    'vendors.phone': 'فون',
    'vendors.email': 'ای میل',
    'vendors.services': 'خدمات',
    'vendors.rating': 'درجہ بندی',
    'vendors.status': 'حالت',
    'vendors.actions': 'اعمال',
    'vendors.edit': 'ترمیم',
    'vendors.viewContracts': 'معاہدات دیکھیں',

    // Procurement Dashboard
    'procurement.title': 'خریداری کا انتظام',
    'procurement.description': 'خریداری کی درخواستوں، منظوریوں، اور وینڈر کے انتخاب کا انتظام',
    'procurement.newRequest': 'نئی درخواست',
    'procurement.totalRequests': 'کل درخواستیں',
    'procurement.awaitingApproval': 'منظوری کا انتظار',
    'procurement.approvedValue': 'منظور شدہ قیمت',
    'procurement.thisMonth': 'اس مہینے',
    'procurement.processed': 'پروسیس شدہ',
    'procurement.requestsProcessed': 'درخواستیں پروسیس شدہ',
    'procurement.procurementRequests': 'خریداری کی درخواستیں',
    'procurement.requestId': 'درخواست کی شناخت',
    'procurement.requestedBy': 'درخواست کنندہ',
    'procurement.amount': 'رقم',
    'procurement.status': 'حالت',
    'procurement.requestDate': 'درخواست کی تاریخ',
    'procurement.actions': 'اعمال',
    'procurement.approve': 'منظور کریں',
    'procurement.reject': 'مسترد کریں',
    'procurement.review': 'جائزہ',

    // Purchase Orders Dashboard
    'purchaseOrders.title': 'خرید کے احکامات',
    'purchaseOrders.description': 'مواد اور خدمات کے لیے خرید کے احکامات بنائیں اور ان کا انتظام کریں',
    'purchaseOrders.createPO': 'PO بنائیں',
    'purchaseOrders.totalPOs': 'کل POs',
    'purchaseOrders.awaitingDelivery': 'ڈیلیوری کا انتظار',
    'purchaseOrders.totalValue': 'کل قیمت',
    'purchaseOrders.thisMonth': 'اس مہینے',
    'purchaseOrders.created': 'بنائے گئے',
    'purchaseOrders.poNumber': 'PO نمبر',
    'purchaseOrders.vendor': 'وینڈر',
    'purchaseOrders.items': 'اشیاء',
    'purchaseOrders.amount': 'رقم',
    'purchaseOrders.status': 'حالت',
    'purchaseOrders.orderDate': 'آرڈر کی تاریخ',
    'purchaseOrders.expectedDelivery': 'متوقع ڈیلیوری',
    'purchaseOrders.actions': 'اعمال',
    'purchaseOrders.viewPO': 'PO دیکھیں',

    // Reports Dashboard
    'reports.title': 'رپورٹس اور تجزیات',
    'reports.description': 'پروجیکٹ کی بصیرت کے لیے جامع رپورٹس اور تجزیات تیار کریں',
    'reports.generateReport': 'رپورٹ تیار کریں',
    'reports.financialReports': 'مالی رپورٹس',
    'reports.salesReports': 'سیلز رپورٹس',
    'reports.expenseReports': 'اخراجات کی رپورٹس',
    'reports.projectReports': 'پروجیکٹ رپورٹس',
    'reports.exportPDF': 'PDF ایکسپورٹ کریں',
    'reports.exportExcel': 'Excel ایکسپورٹ کریں',
    'reports.dateRange': 'تاریخ کی رینج',
    'reports.selectRange': 'تاریخ کی رینج منتخب کریں',
    'reports.reportType': 'رپورٹ کی قسم',
    'reports.selectType': 'رپورٹ کی قسم منتخب کریں',

    // Project Setup Dashboard
    'projectSetup.title': 'پروجیکٹ سیٹ اپ',
    'projectSetup.description': 'بنیادی معلومات، بجٹ، اور سنگ میل کے ساتھ نئے پروجیکٹس کو کنفیگر کریں',
    'projectSetup.newProject': 'نیا پروجیکٹ',
    'projectSetup.activeProjects': 'فعال پروجیکٹس',
    'projectSetup.completedProjects': 'مکمل پروجیکٹس',
    'projectSetup.totalBudget': 'کل بجٹ',
    'projectSetup.projectName': 'پروجیکٹ کا نام',
    'projectSetup.location': 'مقام',
    'projectSetup.startDate': 'شروع کی تاریخ',
    'projectSetup.expectedCompletion': 'متوقع تکمیل',
    'projectSetup.status': 'حالت',
    'projectSetup.progress': 'پیشرفت',
    'projectSetup.actions': 'اعمال',
    'projectSetup.viewProject': 'پروجیکٹ دیکھیں',
    'projectSetup.editProject': 'پروجیکٹ میں ترمیم',

    // Project Milestones Dashboard
    'milestones.title': 'پروجیکٹ کے سنگ میل',
    'milestones.description': 'اہم سنگ میل اور ڈیلیوری کے ذریعے پروجیکٹ کی پیشرفت کو ٹریک کریں',
    'milestones.addMilestone': 'سنگ میل شامل کریں',
    'milestones.totalMilestones': 'کل سنگ میل',
    'milestones.completed': 'مکمل',
    'milestones.inProgress': 'پیشرفت میں',
    'milestones.upcoming': 'آنے والے',
    'milestones.milestoneName': 'سنگ میل کا نام',
    'milestones.project': 'پروجیکٹ',
    'milestones.targetDate': 'ہدف کی تاریخ',
    'milestones.actualDate': 'اصل تاریخ',
    'milestones.status': 'حالت',
    'milestones.progress': 'پیشرفت',
    'milestones.actions': 'اعمال',
    'milestones.markComplete': 'مکمل کا نشان لگائیں',
    'milestones.updateProgress': 'پیشرفت اپڈیٹ کریں',

    // Employee Management Dashboard
    'employees.title': 'ملازمین کا انتظام',
    'employees.description': 'ملازمین کے ریکارڈز، حاضری، اور کارکردگی کی ٹریکنگ کا انتظام',
    'employees.addEmployee': 'ملازم شامل کریں',
    'employees.totalEmployees': 'کل ملازمین',
    'employees.activeEmployees': 'فعال ملازمین',
    'employees.onLeave': 'چھٹی پر',
    'employees.newHires': 'نئے ملازمین',
    'employees.employeeName': 'ملازم کا نام',
    'employees.department': 'شعبہ',
    'employees.position': 'عہدہ',
    'employees.joinDate': 'شمولیت کی تاریخ',
    'employees.phone': 'فون',
    'employees.email': 'ای میل',
    'employees.status': 'حالت',
    'employees.actions': 'اعمال',
    'employees.viewProfile': 'پروفائل دیکھیں',
    'employees.editEmployee': 'ملازم میں ترمیم',

    // Marketing Communication Dashboard
    'marketing.title': 'مارکیٹنگ اور کمیونیکیشن',
    'marketing.description': 'مارکیٹنگ مہمات، کسٹمر کمیونیکیشن، اور لیڈ جنریشن کا انتظام',
    'marketing.newCampaign': 'نئی مہم',
    'marketing.activeCampaigns': 'فعال مہمات',
    'marketing.totalLeads': 'کل لیڈز',
    'marketing.conversionRate': 'تبدیلی کی شرح',
    'marketing.campaignROI': 'مہم کی ROI',
    'marketing.campaignName': 'مہم کا نام',
    'marketing.type': 'قسم',
    'marketing.startDate': 'شروع کی تاریخ',
    'marketing.endDate': 'اختتام کی تاریخ',
    'marketing.budget': 'بجٹ',
    'marketing.spent': 'خرچ شدہ',
    'marketing.leads': 'لیڈز',
    'marketing.conversions': 'تبدیلیاں',
    'marketing.actions': 'اعمال',
    'marketing.viewCampaign': 'مہم دیکھیں',
    'marketing.editCampaign': 'مہم میں ترمیم',

    // Account Statements Dashboard
    'accountStatements.title': 'اکاؤنٹ سٹیٹمنٹس',
    'accountStatements.description': 'مالی اکاؤنٹ سٹیٹمنٹس اور ٹرانزیکشن کی تاریخ دیکھیں اور ان کا انتظام کریں',
    'accountStatements.generateStatement': 'سٹیٹمنٹ تیار کریں',
    'accountStatements.accountBalance': 'اکاؤنٹ بیلنس',
    'accountStatements.monthlyInflow': 'ماہانہ آمد',
    'accountStatements.monthlyOutflow': 'ماہانہ اخراج',
    'accountStatements.pendingTransactions': 'زیر التواء ٹرانزیکشنز',
    'accountStatements.transactionHistory': 'ٹرانزیکشن کی تاریخ',
    'accountStatements.date': 'تاریخ',
    'accountStatements.type': 'قسم',
    'accountStatements.amount': 'رقم',
    'accountStatements.balance': 'بیلنس',
    'accountStatements.reference': 'حوالہ',
    'accountStatements.status': 'حالت',

    // Auto Invoice System Dashboard
    'autoInvoice.title': 'خودکار انوائس سسٹم',
    'autoInvoice.description': 'سنگ میل پر مبنی بلنگ کے لیے خودکار انوائس جنریشن اور انتظام',
    'autoInvoice.createInvoice': 'انوائس بنائیں',
    'autoInvoice.totalInvoices': 'کل انوائسز',
    'autoInvoice.pendingInvoices': 'زیر التواء انوائسز',
    'autoInvoice.paidInvoices': 'ادا شدہ انوائسز',
    'autoInvoice.overdueInvoices': 'مقررہ وقت گزری انوائسز',
    'autoInvoice.invoiceNumber': 'انوائس نمبر',
    'autoInvoice.customer': 'کسٹمر',
    'autoInvoice.amount': 'رقم',
    'autoInvoice.issueDate': 'جاری کرنے کی تاریخ',
    'autoInvoice.dueDate': 'واجبی تاریخ',
    'autoInvoice.status': 'حالت',
    'autoInvoice.actions': 'اعمال',
    'autoInvoice.viewInvoice': 'انوائس دیکھیں',
    'autoInvoice.sendReminder': 'یاد دہانی بھیجیں',

    // Installments Invoicing Dashboard
    'installments.title': 'قسطیں اور انوائسنگ',
    'installments.description': 'قسطوں کے شیڈول اور خودکار انوائس جنریشن کا انتظام',
    'installments.generateInvoices': 'انوائسز تیار کریں',
    'installments.totalInstallments': 'کل قسطیں',
    'installments.dueThisMonth': 'اس مہینے واجب',
    'installments.overdue': 'مقررہ وقت گزری',
    'installments.collected': 'جمع شدہ',
    'installments.installmentSchedule': 'قسطوں کا شیڈول',
    'installments.customer': 'کسٹمر',
    'installments.unit': 'یونٹ',
    'installments.milestone': 'سنگ میل',
    'installments.amount': 'رقم',
    'installments.dueDate': 'واجبی تاریخ',
    'installments.status': 'حالت',
    'installments.actions': 'اعمال',
    'installments.generateInvoice': 'انوائس تیار کریں',
    'installments.recordPayment': 'ادائیگی ریکارڈ کریں'
  }
}

interface InternationalizationProviderProps {
  children: ReactNode
}

export function InternationalizationProvider({ children }: InternationalizationProviderProps) {
  const [language, setLanguageState] = useState<Language>('en')
  const [currency, setCurrencyState] = useState<Currency>('PKR')

  // Load saved settings from localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('jv-flow-language') as Language
    const savedCurrency = localStorage.getItem('jv-flow-currency') as Currency
    
    if (savedLanguage && languages[savedLanguage]) {
      setLanguageState(savedLanguage)
    }
    if (savedCurrency && currencies[savedCurrency]) {
      setCurrencyState(savedCurrency)
    } else {
      // Set PKR as default for Pakistan
      setCurrencyState('PKR')
      localStorage.setItem('jv-flow-currency', 'PKR')
    }
  }, [])

  // Apply RTL/LTR direction to document
  useEffect(() => {
    const direction = languages[language].direction
    document.documentElement.dir = direction
    document.documentElement.lang = language
  }, [language])

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
    localStorage.setItem('jv-flow-language', newLanguage)
  }

  const setCurrency = (newCurrency: Currency) => {
    setCurrencyState(newCurrency)
    localStorage.setItem('jv-flow-currency', newCurrency)
  }

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language][key] || translations['en'][key] || key
    
    // Simple parameter substitution
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{{${param}}}`, params[param])
      })
    }
    
    return translation
  }

  const formatCurrency = (amount: number, currencyCode?: Currency): string => {
    // Use centralized currency configuration for consistent formatting
    return formatCurrencyFn(amount)
  }

  const formatNumber = (number: number): string => {
    try {
      return new Intl.NumberFormat(language === 'ar' ? 'ar-SA' : language === 'ur' ? 'ur-PK' : 'en-US').format(number)
    } catch (error) {
      return number.toLocaleString()
    }
  }

  const direction = languages[language].direction
  const currentCurrency = currencies[currency]
  const currenciesArray = Object.values(currencies)

  return (
    <InternationalizationContext.Provider
      value={{
        language,
        currency,
        currentLanguage: language,
        currentCurrency,
        currencies: currenciesArray,
        direction,
        setLanguage,
        setCurrency,
        t,
        formatCurrency,
        formatNumber,
      }}
    >
      {children}
    </InternationalizationContext.Provider>
  )
}

export function useInternationalization() {
  const context = useContext(InternationalizationContext)
  if (context === undefined) {
    throw new Error('useInternationalization must be used within an InternationalizationProvider')
  }
  return context
}

// Convenience hooks
export function useTranslation() {
  const { t } = useInternationalization()
  return { t }
}

export function useCurrency() {
  const { currency, formatCurrency, setCurrency } = useInternationalization()
  return { currency, formatCurrency, setCurrency }
}